// Patient feature — multiple independent memory banks under one running
// SD Core process. Each Patient owns a separate SQLite file; switching
// patients triggers a Bank.Reopen() at runtime.
//
// Boot semantics:
//
//   - The "default" patient is always present and points at the original
//     SD_BANK_PATH the binary was launched with. Existing single-user
//     installs upgrade transparently — their data shows up under
//     "default" with no migration.
//   - Additional patients live under <data-dir>/patients/<id>/sd_bank.db.
//     Adding a patient is just `mkdir + Bank.Reopen(newPath)` — no schema
//     migration needed because NewBank creates the schema on first open.
//   - The active patient is persisted to <data-dir>/patients.json so a
//     core restart resumes the last selected bank.
//
// Concurrency:
//
//   - PatientStore protects its in-memory registry with sync.RWMutex.
//   - The actual bank swap (Bank.Reopen) is gated by Server.bankSwapMu
//     in main.go — refuses to run if nightly is in progress.
package main

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"sync"
	"time"
)

// Patient is a single named memory bank. ID is opaque (random hex) so
// names can be edited without breaking the on-disk reference. BankPath
// is absolute so a moved data dir doesn't silently re-resolve.
type Patient struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	BankPath  string `json:"bank_path"`
	CreatedAt string `json:"created_at"`
	// IsDefault marks the original SD_BANK_PATH-rooted patient. The
	// default patient cannot be deleted (deleting would orphan its
	// bank file outside this feature's control).
	IsDefault bool `json:"is_default,omitempty"`
}

// PatientStoreSnapshot is the JSON shape persisted to disk. Versioned so
// future migrations don't have to guess.
type PatientStoreSnapshot struct {
	SchemaVersion   int       `json:"schema_version"`
	Patients        []Patient `json:"patients"`
	ActivePatientID string    `json:"active_patient_id"`
	UpdatedAt       string    `json:"updated_at"`
}

// PatientStore is the runtime registry. Thread-safe.
type PatientStore struct {
	mu            sync.RWMutex
	dataDir       string // <data-dir>/patients/ — where new banks live
	registryPath  string // <data-dir>/patients.json
	patients      map[string]Patient
	order         []string // insertion order for stable list display
	activeID      string
	defaultID     string
	// pin: a long-running consumer (typically the benchmark runner) can
	// pin the active patient so concurrent /patients/{id}/activate calls
	// from the dashboard UI return 409 until the pin is released or
	// expires. Pin is identified by an opaque token returned at
	// acquisition; only the holder of that token can release.
	pinPatientID string
	pinToken     string
	pinExpires   time.Time
}

var (
	ErrPatientNotFound       = errors.New("patient not found")
	ErrPatientNameRequired   = errors.New("patient name is required")
	ErrPatientNameDuplicate  = errors.New("patient name already in use")
	ErrPatientCannotDelete   = errors.New("cannot delete the default patient or the active patient")
	ErrPatientInvalidID      = errors.New("invalid patient ID")
	ErrPatientPinned         = errors.New("patient is pinned by an in-progress session; switch refused")
	ErrPatientPinHeld        = errors.New("a pin is already held on a different patient")
	ErrPatientBadPinToken    = errors.New("pin token mismatch")
)

// patientIDPattern guards against directory traversal in patient IDs.
// IDs are autogenerated 16-char hex strings; we only accept that shape.
var patientIDPattern = regexp.MustCompile(`^[a-f0-9]{16}$`)

// newPatientID returns 16 random hex chars (8 bytes of entropy). Collision
// probability over the lifetime of any install is negligible.
func newPatientID() string {
	var b [8]byte
	_, _ = rand.Read(b[:])
	return hex.EncodeToString(b[:])
}

// LoadPatientStore opens (or creates) the patient registry. The
// `defaultBankPath` argument is the path the SD Core binary was launched
// with — it becomes the BankPath of the "default" patient and is the
// active patient on first run.
//
// Existing single-user installs see their bank surface as "default"
// with no migration.
func LoadPatientStore(dataDir, defaultBankPath string) (*PatientStore, error) {
	if dataDir == "" {
		return nil, errors.New("patient store needs a non-empty data dir")
	}
	absData, err := filepath.Abs(dataDir)
	if err != nil {
		return nil, fmt.Errorf("patient store: abs(%q): %w", dataDir, err)
	}
	patientsDir := filepath.Join(absData, "patients")
	if err := os.MkdirAll(patientsDir, 0o755); err != nil {
		return nil, fmt.Errorf("patient store: mkdir %s: %w", patientsDir, err)
	}
	registryPath := filepath.Join(absData, "patients.json")
	ps := &PatientStore{
		dataDir:      patientsDir,
		registryPath: registryPath,
		patients:     map[string]Patient{},
	}

	absDefaultBank, _ := filepath.Abs(defaultBankPath)
	// Read existing registry if any.
	raw, err := os.ReadFile(registryPath)
	if err == nil && len(raw) > 0 {
		var snap PatientStoreSnapshot
		if err := json.Unmarshal(raw, &snap); err != nil {
			return nil, fmt.Errorf("patient registry: parse %s: %w", registryPath, err)
		}
		for _, p := range snap.Patients {
			// Re-derive IsDefault from path equality so a moved data dir
			// can self-correct. Identifies the patient whose BankPath
			// matches the launched-binary's SD_BANK_PATH.
			if absDefaultBank != "" && p.BankPath == absDefaultBank {
				p.IsDefault = true
				ps.defaultID = p.ID
			}
			ps.patients[p.ID] = p
			ps.order = append(ps.order, p.ID)
		}
		if _, ok := ps.patients[snap.ActivePatientID]; ok {
			ps.activeID = snap.ActivePatientID
		}
	}

	// Ensure a default patient always exists pointing at the launched
	// bank file. Idempotent: if one already matches by path, reuse it.
	if ps.defaultID == "" && absDefaultBank != "" {
		// Find any existing patient with matching path before creating.
		for _, id := range ps.order {
			if ps.patients[id].BankPath == absDefaultBank {
				p := ps.patients[id]
				p.IsDefault = true
				ps.patients[id] = p
				ps.defaultID = id
				break
			}
		}
	}
	if ps.defaultID == "" && absDefaultBank != "" {
		id := newPatientID()
		p := Patient{
			ID:        id,
			Name:      "default",
			BankPath:  absDefaultBank,
			CreatedAt: time.Now().UTC().Format(time.RFC3339),
			IsDefault: true,
		}
		ps.patients[id] = p
		ps.order = append(ps.order, id)
		ps.defaultID = id
	}

	if ps.activeID == "" {
		ps.activeID = ps.defaultID
	}

	if err := ps.persistLocked(); err != nil {
		return nil, err
	}
	return ps, nil
}

// persistLocked writes the registry to disk. Caller must hold mu.
// Uses a temp-file-then-rename so a crash mid-write leaves the prior
// file intact.
func (ps *PatientStore) persistLocked() error {
	snap := PatientStoreSnapshot{
		SchemaVersion:   1,
		ActivePatientID: ps.activeID,
		UpdatedAt:       time.Now().UTC().Format(time.RFC3339),
	}
	for _, id := range ps.order {
		snap.Patients = append(snap.Patients, ps.patients[id])
	}
	raw, err := json.MarshalIndent(snap, "", "  ")
	if err != nil {
		return fmt.Errorf("patient registry marshal: %w", err)
	}
	tmp := ps.registryPath + ".tmp"
	if err := os.WriteFile(tmp, raw, 0o644); err != nil {
		return fmt.Errorf("patient registry write %s: %w", tmp, err)
	}
	if err := os.Rename(tmp, ps.registryPath); err != nil {
		return fmt.Errorf("patient registry rename %s -> %s: %w", tmp, ps.registryPath, err)
	}
	return nil
}

// List returns all patients in stable insertion order. Active patient is
// flagged separately via Active() so the client can render the indicator.
func (ps *PatientStore) List() []Patient {
	ps.mu.RLock()
	defer ps.mu.RUnlock()
	out := make([]Patient, 0, len(ps.order))
	for _, id := range ps.order {
		out = append(out, ps.patients[id])
	}
	return out
}

// Get returns one patient by ID. Returns ErrPatientNotFound on miss.
func (ps *PatientStore) Get(id string) (Patient, error) {
	ps.mu.RLock()
	defer ps.mu.RUnlock()
	p, ok := ps.patients[id]
	if !ok {
		return Patient{}, ErrPatientNotFound
	}
	return p, nil
}

// Active returns the currently active patient ID. Always non-empty if
// LoadPatientStore succeeded — there's always at least the default.
func (ps *PatientStore) Active() (Patient, bool) {
	ps.mu.RLock()
	defer ps.mu.RUnlock()
	p, ok := ps.patients[ps.activeID]
	return p, ok
}

// DefaultID returns the ID of the patient whose bank is the original
// SD_BANK_PATH the process was launched with. Used to refuse deletion
// and to provide a "reset" target.
func (ps *PatientStore) DefaultID() string {
	ps.mu.RLock()
	defer ps.mu.RUnlock()
	return ps.defaultID
}

// Create makes a new patient with the given display name. ID and bank
// file path are autogenerated. Bank file is NOT initialised here — the
// caller is responsible for opening a Bank against the returned path
// when this patient is first activated.
func (ps *PatientStore) Create(name string) (Patient, error) {
	name = strings.TrimSpace(name)
	if name == "" {
		return Patient{}, ErrPatientNameRequired
	}
	ps.mu.Lock()
	defer ps.mu.Unlock()
	// Reject duplicate names — would confuse the UI picker. Case-insensitive.
	for _, p := range ps.patients {
		if strings.EqualFold(p.Name, name) {
			return Patient{}, ErrPatientNameDuplicate
		}
	}
	id := newPatientID()
	dir := filepath.Join(ps.dataDir, id)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return Patient{}, fmt.Errorf("patient create: mkdir %s: %w", dir, err)
	}
	p := Patient{
		ID:        id,
		Name:      name,
		BankPath:  filepath.Join(dir, "sd_bank.db"),
		CreatedAt: time.Now().UTC().Format(time.RFC3339),
	}
	ps.patients[id] = p
	ps.order = append(ps.order, id)
	if err := ps.persistLocked(); err != nil {
		// roll back the in-memory addition so the registry stays consistent
		delete(ps.patients, id)
		ps.order = ps.order[:len(ps.order)-1]
		os.RemoveAll(dir)
		return Patient{}, err
	}
	return p, nil
}

// Delete removes a patient and its bank file. Refuses to delete the
// default patient or the currently active patient — caller must activate
// a different patient first.
func (ps *PatientStore) Delete(id string) error {
	if !patientIDPattern.MatchString(id) {
		return ErrPatientInvalidID
	}
	ps.mu.Lock()
	defer ps.mu.Unlock()
	p, ok := ps.patients[id]
	if !ok {
		return ErrPatientNotFound
	}
	if p.IsDefault || id == ps.activeID {
		return ErrPatientCannotDelete
	}
	delete(ps.patients, id)
	// Filter id out of order slice
	newOrder := make([]string, 0, len(ps.order)-1)
	for _, oid := range ps.order {
		if oid != id {
			newOrder = append(newOrder, oid)
		}
	}
	ps.order = newOrder
	if err := ps.persistLocked(); err != nil {
		// Roll back the in-memory deletion before returning. The bank
		// file is left untouched in this case.
		ps.patients[id] = p
		ps.order = append(ps.order, id)
		sort.Strings(ps.order) // not perfect (loses insertion order on rollback) but rare
		return err
	}
	// Delete bank file + any WAL/SHM sidecars + the patient dir.
	bankDir := filepath.Dir(p.BankPath)
	if strings.HasPrefix(bankDir, ps.dataDir) && bankDir != ps.dataDir {
		// Safety check: only rm dirs that live under our managed patients root.
		_ = os.RemoveAll(bankDir)
	}
	return nil
}

// Rename changes a patient's display name. ID and bank_path are
// immutable — those define WHICH bank file holds the data; the name is
// purely cosmetic. Duplicate names (case-insensitive) are rejected so
// the UI picker stays unambiguous.
func (ps *PatientStore) Rename(id, newName string) (Patient, error) {
	newName = strings.TrimSpace(newName)
	if newName == "" {
		return Patient{}, ErrPatientNameRequired
	}
	if !patientIDPattern.MatchString(id) {
		return Patient{}, ErrPatientInvalidID
	}
	ps.mu.Lock()
	defer ps.mu.Unlock()
	p, ok := ps.patients[id]
	if !ok {
		return Patient{}, ErrPatientNotFound
	}
	// No-op rename to its own name — return current state without
	// touching the file. Avoids a fsync round-trip for a no-op.
	if p.Name == newName {
		return p, nil
	}
	// Reject duplicate names against ANY other patient.
	for otherID, other := range ps.patients {
		if otherID == id {
			continue
		}
		if strings.EqualFold(other.Name, newName) {
			return Patient{}, ErrPatientNameDuplicate
		}
	}
	prev := p
	p.Name = newName
	ps.patients[id] = p
	if err := ps.persistLocked(); err != nil {
		// Roll back in-memory rename so the registry stays consistent.
		ps.patients[id] = prev
		return Patient{}, err
	}
	return p, nil
}

// SetActive records a new active patient. Does NOT swap the bank — that
// is the caller's responsibility (Server.SwitchBank). Returns the new
// active patient on success.
//
// Pin enforcement: if a pin is held on a different patient than `id`,
// SetActive returns ErrPatientPinned. Set `force=true` to override the
// pin (used by SystemSwitchBack helpers when a pin's owner has died).
func (ps *PatientStore) SetActive(id string) (Patient, error) {
	return ps.setActiveInternal(id, false)
}

// SetActiveForce overrides any held pin. Use only for cleanup paths
// (e.g. bench restoring prior-active after a crash) — pin holders rely
// on the no-override default behaviour.
func (ps *PatientStore) SetActiveForce(id string) (Patient, error) {
	return ps.setActiveInternal(id, true)
}

func (ps *PatientStore) setActiveInternal(id string, force bool) (Patient, error) {
	if !patientIDPattern.MatchString(id) {
		return Patient{}, ErrPatientInvalidID
	}
	ps.mu.Lock()
	defer ps.mu.Unlock()
	p, ok := ps.patients[id]
	if !ok {
		return Patient{}, ErrPatientNotFound
	}
	if !force && ps.isPinnedLocked() && ps.pinPatientID != id {
		return Patient{}, ErrPatientPinned
	}
	prev := ps.activeID
	ps.activeID = id
	if err := ps.persistLocked(); err != nil {
		ps.activeID = prev
		return Patient{}, err
	}
	return p, nil
}

// isPinnedLocked reports whether a non-expired pin is currently held.
// Caller MUST hold ps.mu (read or write). Expired pins are silently
// treated as no pin — actual cleanup of expired fields happens on the
// next mutation.
func (ps *PatientStore) isPinnedLocked() bool {
	if ps.pinToken == "" {
		return false
	}
	if time.Now().After(ps.pinExpires) {
		return false
	}
	return true
}

// Pin acquires a session pin on the currently-active patient. ttl
// caps how long the pin can be held without renewal — a crashed bench
// won't leave the patient pinned forever. Returns the opaque token
// that subsequent /unpin requests must present.
func (ps *PatientStore) Pin(ttl time.Duration) (string, error) {
	ps.mu.Lock()
	defer ps.mu.Unlock()
	if ps.activeID == "" {
		return "", errors.New("no active patient to pin")
	}
	// If an existing valid pin is held on a different patient, reject.
	if ps.isPinnedLocked() && ps.pinPatientID != ps.activeID {
		return "", ErrPatientPinHeld
	}
	// Fresh token; clobber any expired pin.
	var raw [16]byte
	if _, err := rand.Read(raw[:]); err != nil {
		return "", err
	}
	token := hex.EncodeToString(raw[:])
	ps.pinPatientID = ps.activeID
	ps.pinToken     = token
	if ttl <= 0 {
		ttl = 4 * time.Hour // sensible default for long benches
	}
	ps.pinExpires = time.Now().Add(ttl)
	return token, nil
}

// ForceUnpin clears the pin regardless of token. Used by activatePatient
// when the user explicitly chooses to swap away from a pinned patient —
// pin holder (e.g. bench) is treated as dead.
func (ps *PatientStore) ForceUnpin() {
	ps.mu.Lock()
	defer ps.mu.Unlock()
	ps.pinPatientID = ""
	ps.pinToken     = ""
	ps.pinExpires   = time.Time{}
}

// Unpin releases a pin if the token matches. Token mismatch returns
// ErrPatientBadPinToken so a stray client can't release someone else's
// pin. Releasing a missing pin is a no-op (idempotent).
func (ps *PatientStore) Unpin(token string) error {
	ps.mu.Lock()
	defer ps.mu.Unlock()
	if !ps.isPinnedLocked() {
		// Already released or expired — caller's goal already met.
		return nil
	}
	if ps.pinToken != token {
		return ErrPatientBadPinToken
	}
	ps.pinPatientID = ""
	ps.pinToken     = ""
	ps.pinExpires   = time.Time{}
	return nil
}

// PinState reports the current pin state. Used by the API to surface
// the locked indicator to the UI.
func (ps *PatientStore) PinState() (heldByID string, expiresAt time.Time) {
	ps.mu.RLock()
	defer ps.mu.RUnlock()
	if !ps.isPinnedLocked() {
		return "", time.Time{}
	}
	return ps.pinPatientID, ps.pinExpires
}
